export const GET_USER_ASSIGN_TASK_SAGA = "GET_USER_ASSIGN_TASK_SAGA";
export const GET_USER_ASSIGN_TASK = "GET_USER_ASSIGN_TASK";

export const DELETE_USER_JIRA = "DELETE_USER_JIRA";
export const EDIT_USER_INFO_SAGA = "EDIT_USER_INFO";
export const GET_USER_SAGA_SEARCH = "GET_USER_SAGA_SEARCH";
